import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CarrinhoProvider } from "@/context/CarrinhoContext";
import Header from '@/components/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FlashFoods",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:{
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <CarrinhoProvider>
          <Header/>
          {children}
        </CarrinhoProvider>
      </body>
    </html>
  );
}
